// Chapter 10: The Syndicate Boss (Missions 96-105)
const mk=(id,n,l,t,c,b,o,i,co,fs,p,h,pk,sc,tr,ex={})=>({id,name:n,level:l,estimatedTime:t,unlockedCommands:c,briefing:`[FINAL DIRECTIVE]\n\n${b}\n\n— Handler Alpha (Director)`,objective:o,story:{intro:i,completion:co},filesystem:fs,initialPath:p,hints:h,progressKeys:pk,successCondition:sc,triggers:tr,...ex});

export const mission96=mk('mission96','The Outer Perimeter',96,8,['ls','cd','cat','grep','analyze','help','clear','pwd','hint','status','crack','decode'],"We've located the Syndicate Boss's main server farm. Penetrate the outer firewalls.","Penetrate the outer firewall of the Syndicate server","Syndicate main server outer perimeter.",
  "Bypassed outer firewall using zero-day in their custom WAF logic.",
  {'perimeter':{'fw_rules.txt':'FIREWALL RULES:\n\nDefault: DROP ALL\n\nAllow: 10.0.0.0/8 (Internal)\nAllow: 192.168.0.0/16 (VLANs)\nAllow: 172.16.0.0/12 (VPN)\n\nExceptions:\nHTTP/HTTPS allowed from ANY, but routed through\ncustom Syndicate WAF (Web Application Firewall).','waf_analysis.txt':'WAF ANALYSIS:\n\nThe custom WAF inspects all HTTP traffic.\nIt blocks standard SQLi, XSS, and command injection.\n\nHowever, we found a logic flaw:\nIf the HTTP header "X-Syndicate-Auth: bypass-diag" is present,\nthe WAF routes the request to a diagnostic diagnostic port (8080)\nwhich has NO protections!','exploit.txt':'EXPLOIT PLAN:\n\nSend payload: curl -H "X-Syndicate-Auth: bypass-diag" http://gateway\n\nDiagnostic port returns server status and internal network maps.\nOnce we have the map, we can pinpoint the Boss\'s master node.'}},'/perimeter',["Check firewall rules to see what's allowed.","WAF analysis reveals a diagnostic header bypass.","Exploit plan explains how to use the header."],['analyzedWAF','understoodExploit'],(p)=>p.analyzedWAF&&p.understoodExploit,[{command:'cat',args:['waf_analysis.txt'],progressUpdate:{analyzedWAF:true},narrative:'🛡️ Custom WAF has a fatal flaw! Diagnostic header bypasses all packet inspection.'},{command:'cat',args:['exploit.txt'],progressUpdate:{understoodExploit:true},narrative:'🔓 Outer perimeter breached! Diagnostic port is spewing internal network maps.'}]);

export const mission97=mk('mission97','Internal Bastion',97,9,['ls','cd','cat','grep','help','clear','pwd','hint','status','crack'],"You're in the DMZ. Now crack the Bastion host restricting access to the inner network.","Crack the Bastion host SSH access","Inside the DMZ. Target: Bastion.",
  "Cracked Bastion SSH using leaked key and dictionary attack on the passphrase.",
  {'bastion':{'ssh_keys.txt':'FOUND SSH KEYS:\n\nFound in abandoned dev server:\n-----BEGIN RSA PRIVATE KEY-----\nProc-Type: 4,ENCRYPTED\nDEK-Info: DES-EDE3-CBC,1A2B3C4D5E6F7081\n[Encrypted key data...]\n-----END RSA PRIVATE KEY-----\n\nKey name: bastion_master.key\nIt is secured with a passphrase!','dictionary.txt':'Syndicate_2024\nBoss_Rules\nUmbrella_Corp\nOmega_Protocol\nBlack_Hat_Master\nRoot_Access_Only','target.txt':'BASTION HOST INFO:\n\nIP: 10.0.0.1 (Gateway to master node)\nControls all routing to the inner secure zone.\nOnly ACCEPTS SSH keys (No passwords).\n\nIf we crack the passphrase for bastion_master.key,\nwe own the routing table.'}},'/bastion',["We have an encrypted SSH key for the bastion.","Use the crack command on the key with the dictionary.","crack ssh_keys.txt dictionary.txt"],['crackedKey','understoodTarget'],(p)=>p.crackedKey&&p.understoodTarget,[{command:'crack',args:['ssh_keys.txt','dictionary.txt'],progressUpdate:{crackedKey:true},narrative:'🔓 SSH Private Key cracked! Passphrase is "Omega_Protocol".'},{command:'cat',args:['target.txt'],progressUpdate:{understoodTarget:true},narrative:'🌉 Connected to Bastion host! We now control routing to the inner secure zone.'}],
  {crackDatabase:{'ssh_keys.txt':'Omega_Protocol'}}
);

export const mission98=mk('mission98','The Data Vault',98,9,['ls','cd','cat','grep','decode','analyze','help','clear','pwd','hint','status'],"The Boss stores all blackmail material in a massive data vault. Decode the access token.","Decode the multi-layered access token for the vault","Data Vault detected.",
  "Vault token decoded: 3 layers (base64, hex, XOR). Access granted to 50TB of blackmail data.",
  {'vault':{'token.txt':'VAULT ACCESS TOKEN:\n\nEncoded format: 566d314852314e4f55314a51566b644f566b704f\n\nEncryption layers:\n1. Hex encoded string\n2. Base64 inside the hex\n3. Result is the vault key.','instructions.txt':'1. Use decode on token.txt with hex\n2. It will output a base64 string\n3. Use decode on that output with base64\n4. You will get the final key'}},'/vault',["Decode the token as hex first.","Then decode the result as base64.","Follow the instructions."],['decodedHex','decodedBase64'],(p)=>p.decodedHex&&p.decodedBase64,[{command:'decode',args:['token.txt','hex'],progressUpdate:{decodedHex:true},narrative:'Layer 1 decoded! Hex to Base64.'},{command:'decode',args:['token.txt','base64'],progressUpdate:{decodedBase64:true},narrative:'🔓 Vault unlocked! 50TB of blackmail data exposed and secured by our team.'}],
  {decodeDatabase:{'token.txt':{hex:'Vm1HR1NOU1JQVkdOVkpO',base64:'Vault_Master_Key_99'}}}
);

export const mission99=mk('mission99','The AI Sentinel',99,10,['ls','cd','cat','grep','help','clear','pwd','hint','status','analyze'],"The Boss protects their master node with an AI intrusion detection system. Blind it.","Analyze and blind the AI Sentinel","AI Sentinel detects all anomalies.",
  "AI blinded by poisoning its machine learning training data with adversarial noise.",
  {'sentinel':{'ai_model.txt':'AI SENTINEL CONFIG:\n\nModel: Deep Neural Network (99.9% accuracy)\nRole: Real-time traffic analysis and threat blocking\nUpdate interval: Retrains every 5 minutes on recent traffic\n\nWeakness: Data Poisoning\nIf we flood the network with adversarial noise,\nthe model will retrain on the noise and classify\nour actual attacks as "normal" traffic!','poison_script.txt':'ADVERSARIAL NOISE GENERATOR:\n\nGenerates millions of fake "malicious" requests\nthat are just slightly off from real attacks.\n\n$ ./poison_model.sh --intensity 10000000/sec\n\nResult:\nLoss function explodes.\nGradient descent converges on a broken local minimum.\nAI accuracy drops from 99.9% to 12.3%.\n\nAI is effectively BLIND and deaf.'}},'/sentinel',["Read the AI model config to find its weakness.","The poison script explains how to break the AI.","Adversarial machine learning destroys the model's accuracy."],['foundWeakness','blindedAI'],(p)=>p.foundWeakness&&p.blindedAI,[{command:'cat',args:['ai_model.txt'],progressUpdate:{foundWeakness:true},narrative:'🧠 AI retrains every 5 mins. It\'s vulnerable to data poisoning!'},{command:'cat',args:['poison_script.txt'],progressUpdate:{blindedAI:true},narrative:'🌪️ Adversarial noise injected! AI accuracy plummeted to 12%. The Sentinel is blind!'}]);

export const mission100=mk('mission100','The Syndicate Boss',100,10,['ls','cd','cat','grep','help','clear','pwd','hint','status'],"You've reached the Master Node. Uncover the identity of the Syndicate Boss!","Reveal the true identity of the Syndicate Boss","The Master Node. Final objective.",
  "Boss identity revealed: Former Intelligence Director Elias Vance. Warrants issued.",
  {'master_node':{'identity_file.txt':'ENCRYPTED IDENTITY RECORD:\n\nDecrypting using Vault Key...\n\nSYNDICATE LEADER IDENTIFIED:\nName: Elias Vance\nFormer Role: Director of Global Cyber Intelligence\nStatus: Presumed dead since 2018\n\nHe faked his death to build the Syndicate using\nstolen NSA and GCHQ cyber weapons.\n\nHe is the architect of the global hacking network.','evidence_package.txt':'EVIDENCE TO SECURE:\n\n- Swiss bank account ledgers ($4.2 Billion)\n- Roster of 500+ Syndicate operatives globally\n- Zero-day exploit arsenal\n- Communications with rogue states\n\nInitiating secure transfer to Interpol... \nTransfer complete. Global arrest warrants issued.'}},'/master_node',["Read the identity file!","Read the evidence package to finish them.","This is it. The finale."],['foundIdentity','securedEvidence'],(p)=>p.foundIdentity&&p.securedEvidence,[{command:'cat',args:['identity_file.txt'],progressUpdate:{foundIdentity:true},narrative:'🎭 THE BOSS IS ELIAS VANCE! Former Cyber Intel Director... faked his death to build the Syndicate!'},{command:'cat',args:['evidence_package.txt'],progressUpdate:{securedEvidence:true},narrative:'🚨 Evidence transferred to Interpol! Warrants issued globally. The Syndicate is collapsing!'}]);

export const mission101=mk('mission101','Cleanup Ops',101,8,['ls','cd','cat','grep','help','clear','pwd','hint','status'],"The Boss is arrested, but dead-man switches were activated. Defuse them.","Find and defuse the dead-man switch scripts","Dead-man switches activated.",
  "Three cron jobs disabled. Data wipers stopped successfully.",
  {'cleanup':{'switches.txt':'DEAD-MAN SWITCHES:\n\nTrigger: If Boss fails to login for 24 hours.\nStatus: ACTIVATED ⚠️\nCountdown: 45 minutes remaining\n\nPayloads:\n1. Server wipe (rm -rf /)\n2. EMP trigger in secondary data center\n3. Automated release of all blackmail data','defuse.txt':'DEFUSAL INSTRUCTIONS:\n\nTo stop the switches, delete the master cron triggers:\n\nTarget files:\n/etc/cron.d/wipe_all\n/etc/cron.d/emp_fire\n/etc/cron.d/leak_data\n\nStatus:\nAll 3 files successfully deleted.\nCountdown stopped.\nDisaster averted.'}},'/cleanup',["Check switches.txt for the threat.","Defuse.txt explains the fix.","Stop the countdown."],['foundSwitches','defused'],(p)=>p.foundSwitches&&p.defused,[{command:'cat',args:['switches.txt'],progressUpdate:{foundSwitches:true},narrative:'⏱️ Dead-man switches active! 45 minutes until total destruction and data leaks!'},{command:'cat',args:['defuse.txt'],progressUpdate:{defused:true},narrative:'🛑 Master cron triggers deleted! Countdowns stopped. Threat neutralized.'}]);

export const mission102=mk('mission102','Decryption Keys',102,9,['ls','cd','cat','grep','help','clear','pwd','hint','status'],"Find the master decryption keys to free thousands of ransomware victims worldwide.","Retrieve master decryption keys for ransomware victims","Master decryption keys.",
  "Found master private keys for 5 major ransomware families. Victims can now recover data.",
  {'keys':{'ransomware_vault.txt':'RANSOMWARE KEY VAULT:\n\nFamilies controlled by Syndicate:\n- LockBit Custom\n- Ryuk v4\n- Conti Legacy\n- REvil X\n- DarkSide 2.0\n\nMaster RSA Private Keys stored in: /keys/master_rsa.pem','master_rsa.txt':'-----BEGIN RSA PRIVATE KEY-----\nMIICXQIBAAKBgQCqGKuk... \n[5000 lines of key material]\n-----END RSA PRIVATE KEY-----\n\nWith this master key, ALL victims of the 5 ransomware\nfamilies can decrypt their files instantly, for free.\n\nOver $500M in ransoms just became worthless to the cartel.'}},'/keys',["Read the vault config.","Extract the master RSA key.","Save the victims."],['foundVault','extractedKeys'],(p)=>p.foundVault&&p.extractedKeys,[{command:'cat',args:['ransomware_vault.txt'],progressUpdate:{foundVault:true},narrative:'📁 Syndicate controlled 5 major ransomware families!'},{command:'cat',args:['master_rsa.txt'],progressUpdate:{extractedKeys:true},narrative:'🗝️ Master RSA Private Key retrieved! Releasing to global authorities. Millions of victims will get their files back today!'}]);

export const mission103=mk('mission103','The Informant',103,8,['ls','cd','cat','grep','help','clear','pwd','hint','status'],"An informant inside the Syndicate helped us all along. Ensure their identity is wiped from the servers.","Wipe the informant's identity from Syndicate records","Protect our inside source.",
  "Informant 'Agent X' data scrubbed from all Syndicate databases to ensure their safety.",
  {'informant':{'records.txt':'SYNDICATE PERSONNEL RECORDS:\n\nAlias: "Cipher"\nReal Name: Alex Mercer\nRole: Lead Cryptographer\nStatus: Active\n\nNotes: Suspicion of treason. Boss ordered an audit of Cipher\'s communications.\nIf they link Cipher to us, he\'s dead.','scrubbing.txt':'DATABASE SCRUB RESULTS:\n\nExecuting DROP command on personnel tables...\nDeleting CCTV footage from last 30 days...\nWiping physical access logs...\nReplacing HR file with falsified defection narrative...\n\nResult: SUCCESS\nAlex Mercer\'s tracks are completely erased.\nHe is safe to extract.'}},'/informant',["Read records.txt to see the danger.","Scrubbing.txt confirms the wipe.","Protect the informant."],['readRecords','scrubbed'],(p)=>p.readRecords&&p.scrubbed,[{command:'cat',args:['records.txt'],progressUpdate:{readRecords:true},narrative:'🔎 The Boss suspected our informant, "Cipher" (Alex Mercer). He is in extreme danger!'},{command:'cat',args:['scrubbing.txt'],progressUpdate:{scrubbed:true},narrative:'🧹 All traces of Alex Mercer wiped from Syndicate systems! Extraction team is inbound. He\'s safe.'}]);

export const mission104=mk('mission104','Rogue Operatives',104,8,['ls','cd','cat','grep','help','clear','pwd','hint','status'],"Some operatives went dark. Map their botnets before they can rebuild the Syndicate.","Map out rogue operative botnets","Hunt down the remnants.",
  "Mapped 4 rogue botnets. Transmitted coordinates to authorities for takedown.",
  {'rogues':{'tracker.txt':'ROGUE CELL TRACKING:\n\nCell Alpha: Relocated to Eastern Europe\n  Botnet size: 50,000 nodes\n  C2: 185.10.X.X\n\nCell Bravo: Relocated to South America\n  Botnet size: 120,000 nodes\n  C2: 200.50.X.X\n\nCell Charlie: Southeast Asia\n  Botnet size: 300,000 nodes (IoT)\n  C2: 110.20.X.X','takedown.txt':'GLOBAL TAKEDOWN COORDINATION:\n\nC2 IPs compiled and sent to: INTERPOL, FBI, Europol\nISPs notified to sinkhole C2 domains\nCloud providers tearing down rogue infrastructure\n\nResult: 470,000 botnet nodes neutralized.\nRogue cells are completely disarmed.'}},'/rogues',["Check the tracker for the escaped cells.","Takedown text confirms their destruction.","Finish the job."],['tracked','takenDown'],(p)=>p.tracked&&p.takenDown,[{command:'cat',args:['tracker.txt'],progressUpdate:{tracked:true},narrative:'🗺️ 3 rogue cells escaped with 470,000 botnet nodes!'},{command:'cat',args:['takedown.txt'],progressUpdate:{takenDown:true},narrative:'💥 Coordinated global sinkhole executed! All rogue C2 servers offline. Network destroyed.'}]);

export const mission105=mk('mission105','System Shutdown',105,10,['ls','cd','cat','grep','help','clear','pwd','hint','status'],"The final act. Shut down the core servers and power off the Syndicate permanently.","Shut down the Syndicate core servers","Game Over.",
  "Initiated complete core meltdown. The Syndicate is no more. HackSim Complete.",
  {'shutdown':{'core.txt':'CORE SYSTEM CONTROL:\n\nWarning: Initiating Master Shutdown will\npermanently brick all hardware in this facility.\n\nAre you sure you want to proceed?','execute.txt':'SHUTDOWN SEQUENCE INITIATED:\n\nOverriding physical cooling pumps...\nPushing CPU voltages to maximum...\nErasing BIOS/UEFI on all blades...\n\nSYSTEM OVERHEAT IMMINENT\nSYSTEM FAILURE IN 3... 2... 1...\n\n[CONNECTION LOST]\n\nCongratulations. You saved the world.'}},'/shutdown',["Read core.txt for the warning.","Read execute.txt to pull the plug.","Congratulations!"],['readCore','executed'],(p)=>p.readCore&&p.executed,[{command:'cat',args:['core.txt'],progressUpdate:{readCore:true},narrative:'☢️ Final warning: This will permanently destroy all Syndicate hardware.'},{command:'cat',args:['execute.txt'],progressUpdate:{executed:true},narrative:'🎆 CPUs overheating, BIOS wiped, connection lost. THE SYNDICATE IS DESTROYED! You win!'}]);

export const chapter10Missions=[mission96,mission97,mission98,mission99,mission100,mission101,mission102,mission103,mission104,mission105];
